version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: rfgo # 원하는 데이터베이스 이름으로 변경하세요.
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: